### ISSUE TITLE
Read Object Line by Line via Presigned URL

### ISSUE THREAD

**Issue by h2cone** [anergictcell/s3reader#3]
First of all, great work!

While using S3 Object Lambda for large objects, I noticed that the Rust version seems to only retrieve objects via a Presigned URL. Is there a way to read the object line by line using the Presigned URL?

**Comment by anergictcell** [comment]
Hi h2cone,

I'm not sure if I understand your problem correctly. In theory you can read on S3 object line by line with this library. Depending on the file, this might not be very performant, because you will have plenty of network roundtrips. But it is possible.
Or did I misunderstand your question?

**Comment by h2cone** [comment]
> Hi h2cone,
> 
> I'm not sure if I understand your problem correctly. In theory you can read on S3 object line by line with this library. Depending on the file, this might not be very performant, because you will have plenty of network roundtrips. But it is possible. Or did I misunderstand your question?

I was able to solve part of the issue using reqwest and StreamReader, but I still appreciate your response. Thank you!
